In [712]:
import pandas as pd
import numpy as np

import text_task


from importlib import reload
reload (text_task)

<module 'text_task' from 'C:\\Users\\dfleetwood\\PycharmProjects\\text_analysis\\text_analysis\\text_task.py'>

In [2]:
imdb = pd.read_csv ("imdb_master.csv", encoding = "latin")

In [3]:
imdb.columns

Index(['Unnamed: 0', 'type', 'review', 'label', 'file'], dtype='object')

In [4]:
imdb.shape

(100000, 5)

In [5]:
imdb = imdb [imdb.label != "unsup"]

In [6]:
imdb.shape

(50000, 5)

In [7]:
#imdb [imdb.type == "train"].review

In [8]:
#imdb.review 

In [714]:
imdb_task = text_task.TextTask()

In [715]:
train_idx = np.random.RandomState(423423).choice(range(imdb [imdb.type == "train"].shape[0]), 5000, replace=False)

In [716]:
imdb_task.add_text(imdb [imdb.type == "train"].review.values [train_idx], "train")

In [717]:
test_idx = np.random.RandomState(6345345).choice(range(imdb [imdb.type == "train"].shape[0]), 2000, replace=False)

In [718]:
imdb_task.add_text(imdb [imdb.type == "test"].review.values[test_idx], "test")

In [720]:
imdb_task.clean_text ("train")

In [721]:
imdb_task.clean_text ("test")

In [689]:
imdb_task.save ("imdb_text.pkl")

In [78]:
imdb_task = text_task.load ("imdb_text.pkl")

In [19]:
imdb_task.texts ['test'][0]

'the director was probably still in his early learning stages when he tried his hand at westerns have a look at the outfits everybody looks well scrubbed well brushed well dressed and well ironed as though ready for church even the horses look well groomed and shiny this is a western for crying out loud it s supposed to look dusty nasty and sweaty and then there s the amateurish acting of the females in this bird the whole lot a dozen or so all pretty and well endowed were just freshly raped and widowed but hardly a tear flows instead they all look with great interest if not downright lust at the newly arrived magnificent seven who they subsequently feed bandage and comfort with love during their battles with the bandits the same directing criticism goes for lee van cleef who does a reasonable good acting job our lee playing the law just lost his dear wife but lee hard as organic rock shows no emotion whatsoever and finds himself within days of his spouse s demise in the arms of a juic

In [39]:
imdb_task.fit_tf_idf('train')

In [40]:
imdb_task.get_tf_idf('train').shape

(5000, 30000)

In [41]:
imdb_task.transform_tf_idf('train', 'test')

In [42]:
imdb_task.get_tf_idf('test').shape

(2000, 30000)

In [487]:
#imdb_task.get_tf_idf('test')

In [488]:
#tf_idf.fit (imdb_task.texts ['train'][0:10])

In [489]:
#X = tf_idf.fit_transform(imdb_task.texts ['train'][0:100])

In [490]:
#X.shape

In [491]:
#Y = tf_idf.transform(imdb_task.texts ['train'][101:150])

In [690]:
#train_idx

In [724]:
imdb_task.train_embed_model('train', 'w2v_model', model_type='w2vec')

Training model


In [492]:
#imdb_task.get_tf_idf('train').shape

In [493]:
#imdb_task.transform_tf_idf(fit_model_tag= 'train', to_text_tag= 'test')

In [494]:
#imdb_task.get_tf_idf(text_tag='test').shape

In [229]:
import sklearn.linear_model


In [45]:
log_reg = sklearn.linear_model.LogisticRegression (C=0.1, solver='newton-cg', random_state=40)

In [46]:
train_labs = np.array (imdb.label.values == "pos")*1
train_labs = train_labs [train_idx]

In [47]:
test_labs = np.array (imdb.label.values == "pos")*1
test_labs = test_labs [test_idx]

In [48]:
log_reg.fit (imdb_task.get_tf_idf(text_tag='train'), train_labs)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=40, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [49]:
log_reg.score(imdb_task.get_tf_idf(text_tag='train'), train_labs)

0.8432

In [50]:
log_reg.score(imdb_task.get_tf_idf(text_tag='test'), test_labs)

0.8065

In [64]:
imdb_task.emb_models = models_back

In [65]:
imdb_task.embed_text('train', 'glove-twitter-25')

Embedding 5000 texts
0
1000
2000
3000
4000


In [26]:
#models_back = imdb_task.emb_models

In [66]:
word_sims, agg_sims, ordering = imdb_task.embedding_lookup('train', 'glove-twitter-25', 'romantic', 
                                                           lookup_agg_method = np.mean, 
                                                           text_agg_method = np.max)

0
1000
2000
3000
4000


In [67]:
coloured_texts = imdb_task.colour_attention ('train', word_sims)

0
1000
2000
3000
4000


In [60]:
imdb_task.print_coloured_text (np.array (coloured_texts) [ordering [0:10]])

In [76]:
stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
stopwords_set = set (stopwords)

In [80]:
np.array (imdb_task.texts_tok ['train'][0]) in np.array (stopwords_set)

False

In [71]:
len (imdb_task.embeds['train']['glove-twitter-25'][0])

54

In [81]:
np.setdiff1d(imdb_task.texts_tok ['train'][0],stopwords)

array(['americans', 'anyone', 'brits', 'comedy', 'completely', 'could',
       'doubt', 'eddie', 'enjoy', 'ever', 'everyone', 'funniest', 'funny',
       'genius', 'hilarious', 'izzard', 'laugh', 'natural', 'picks',
       'seen', 'sit', 'stand', 'style', 'watch'], dtype='<U10')

In [89]:
#imdb_task.texts_tok ['train'][0]

In [101]:
np.average (np.array (imdb_task.embeds['train']['glove-twitter-25'][1]) [np.where (~np.isin (imdb_task.texts_tok ['train'][1],stopwords))[0]], axis = 0)

(25,)

In [94]:
np.where (~np.isin (imdb_task.texts_tok ['train'][0],stopwords))[0]

array([ 5,  6,  8, 11, 12, 13, 14, 17, 19, 21, 22, 24, 28, 30, 31, 33, 34,
       36, 38, 39, 40, 45, 49, 50, 53], dtype=int64)

In [106]:
text_embeds = imdb_task.embeds['train']['glove-twitter-25']
text_tok = imdb_task.texts_tok ['train']

sent_embs = []
for i in range (len (text_tok)):
    if (i % 1000) == 0:
        print (i)
    assert (len (text_embeds[i]) == len (text_tok[i]))
    sent_embs.append (np.average (np.array (text_embeds[i]) [np.where (~np.isin (text_tok[i],stopwords))[0]], axis = 0))
    
sent_embs = np.array (sent_embs)

0
1000
2000
3000
4000


In [107]:
sent_embs.shape

(5000, 25)

In [49]:
from IPython.display import HTML as html_print

In [50]:
html_print (" <br> ".join (np.array (coloured_texts) [ordering [0:10]]))

In [135]:
embeds = imdb_task.embeds ['train']['glove-twitter-25']

In [299]:
for i in range (len (embeds)):
    a = cosine_similarity(embeds [i], lookup_text_emb)

In [544]:
pretrained_model_tag = 'glove-twitter-25'

In [567]:
lookup_text = 'violent action'

In [568]:
text_tag = 'train'

In [558]:
imdb_task.embeds.keys()

dict_keys(['train'])

In [563]:
lookup_agg_method = np.mean

In [576]:
text_agg_method = np.max

In [592]:
# imdb_task.load_embedding_model(pretrained_model_tag)
# 
# emb_model = imdb_task.emb_models [pretrained_model_tag]
# 
# lookup_text_tok = imdb_task._tokenize([lookup_text])
# #print (lookup_text_tok)
# emb_length = emb_model ['a'].shape [0]
# lookup_text_emb = imdb_task._embed_line(lookup_text_tok, emb_model, emb_length)
# lookup_text_emb = np.array (lookup_text_emb)
# lookup_text_emb = lookup_text_emb.squeeze (0)
# 
# embs = imdb_task.embeds [text_tag][pretrained_model_tag]
# 
# emb_sims = []
# emb_sims_max = []
# for i in range(0, len(embs)):
#     if (i % 1000) == 0:
#         print(i)
# 
#     lin_cos_sim = cosine_similarity(embs[i], lookup_text_emb)
#     lin_cos_sim = lookup_agg_method(lin_cos_sim, axis=1)
#     emb_sims.append(lin_cos_sim)
#     max_sims = text_agg_method (lin_cos_sim)
#     emb_sims_max.append(max_sims)
# 
# emb_sims = np.array (emb_sims)
# emb_sims_max = np.array (emb_sims_max)
# 
# ordering = np.argsort(-emb_sims_max)

In [99]:
imdb_task.emb_models['glove-twitter-25']['romance']

array([ 0.010751, -0.72868 ,  0.02601 ,  0.69312 ,  0.97722 , -0.22981 ,
        1.5951  ,  0.14071 ,  0.27606 , -1.4623  ,  0.03556 , -0.46209 ,
       -2.2854  , -0.40581 , -0.27038 ,  0.51349 , -0.46135 ,  0.38363 ,
        0.54332 , -0.1618  , -0.64526 , -0.14408 , -0.9408  , -0.32212 ,
        0.64805 ], dtype=float32)

In [117]:
word_sims, max_sims, ordering = imdb_task.embedding_lookup('train', 'glove-twitter-25', 'romantic', 
                                                           lookup_agg_method = np.mean, 
                                                           text_agg_method = np.max)

0
1000
2000
3000
4000


In [101]:
ordering

array([3041, 4262, 4036, ..., 2449,  302, 2236], dtype=int64)

In [118]:
attention_weights = word_sims

In [119]:
subset = None

In [120]:
text_tag = "train"

In [121]:
from sklearn.utils.extmath import softmax

text_tok = imdb_task.texts_tok [text_tag]

if subset is not None:
    text_tok = text_tok [subset]
    attention_weights = attention_weights [subset]

def cstr(s, color='black'):
    return "<text style=background-color:{}>{}</text>".format(color, s)


def norm (x):
    return ((x-min(x))/(max(x)-min(x)))
    

red = np.array([255, 0, 0])
green = np.array([0, 255, 0])
blue = np.array([0, 0, 255])
red = np.round(red).astype("int64")
blue = np.round(blue).astype("int64")
green = np.round(green).astype("int64")

col = green

coloured_sents = []
for ref in range (len (text_tok)):
    col_sent = []
    attn_weights = attention_weights [ref]
    attn_weights = norm(attn_weights)**5
    #attn_weights = softmax(np.array (attn_weights))

    #attn_weights = attn_weights [0,:]
    
    if (ref % 1000) == 0:
        print(ref)

    for i in range(0, len(text_tok [ref])):

        assert (len (attn_weights) == len (text_tok[ref]))

        alpha = np.array(attn_weights[i]) * 255

        alpha = np.round(alpha).astype("int64")

        col_word = cstr(text_tok[ref][i],
                        '#{:02x}{:02x}{:02x}{:02x}'.format(col[0], col[1], col[2], alpha))

#         if (i % 10) == 0:
#             col_sent.append(" <br> " + col_word)
#         else:
        col_sent.append(col_word)

    coloured_sents.append(" ".join(col_sent))

0
1000
2000
3000
4000


In [41]:
#alpha

In [33]:
#attn_weights

In [71]:
#coloured_sents [0]

In [36]:
#coloured_sents = imdb_task.colour_attention ('train', word_sims)

In [122]:
from IPython.display import HTML as html_print

In [123]:
html_print (" <br> ".join (np.array (coloured_sents) [ordering [0:10]]))

In [602]:
np.array (imdb_task.texts['train'])[ordering]

array(['this was excellent touching action packed and perfect for kurt russel i loved this movie it deserves more than or so stars this movie is the story of an obsolete soldier who learns there is more to life than soldiering and people who learn that there is a time for fighting a need to defend i cried laughed and mostly sat in awe of this story good writing job for an action flick and the plot was appropriate and fairly solid the ending wasn t twisty but it was still excellent if you like escape from new york or rooting for the underdog this movie is for you not an undue amount of gore or violence it was not difficult to watch in that respect something for everyone',
       'after gorging myself on a variety of seemingly immature movies purchased on ex rental dvds i figured that the time was right for a little serious drama and who better to provide it than sam mendes for a number of reasons american beauty doesn t appeal to me as much as this film which is easily the darkest thing

In [595]:
#np.mean (word_sims[0])

In [596]:
#max_sims_a = [np.max (x) for x in word_sims]

In [597]:
#ordering = np.argsort (-np.array (max_sims_a))

In [461]:
#np.array (imdb_task.texts ['train']) [ordering]

In [462]:
embs = imdb_task.embeds['train']['glove-twitter-25']

In [463]:
emb_model = imdb_task.emb_models ['glove-twitter-25']

In [464]:
lookup_text = "action"

In [465]:
lookup_text_tok = lookup_text.split (" ")

In [466]:
emb_length = emb_model ['a'].shape [0]

In [467]:
lookup_text_emb = imdb_task._embed_line (lookup_text_tok, emb_model, emb_length)

In [468]:
from sklearn.metrics.pairwise import cosine_similarity

In [469]:
lin_cos_sim = cosine_similarity (embs[0], lookup_text_emb)

In [209]:
np.mean (lin_cos_sim, axis = 1)

array([0.7064953 , 0.589067  , 0.6213429 , 0.59356546, 0.7458868 ,
       0.589079  , 0.69953656, 0.6129971 , 0.7839712 , 0.5932517 ,
       0.66459924, 0.7034769 , 0.63008404, 0.43208623, 0.20198816,
       0.7342957 , 0.5363021 , 0.67736506, 0.5144093 , 0.518046  ,
       0.7123766 , 0.584567  , 0.49265343, 0.70720315, 0.56344473,
       0.7123766 , 0.7157514 , 0.63224745, 0.73522794, 0.7342957 ,
       0.5645032 , 0.47523054, 0.70720315, 0.5645032 , 0.61516124,
       0.5932517 , 0.6221181 , 0.69119936, 0.6563445 , 0.6570064 ,
       0.523802  , 0.66994524, 0.7064953 , 0.70720315, 0.6591221 ,
       0.55855596, 0.70603883, 0.5363021 , 0.5598166 , 0.72054225,
       0.60620964, 0.67439103, 0.49265248, 0.6046612 ], dtype=float32)

In [193]:
np.max (lin_cos_sim)

0.8427038

In [218]:
lookup_agg_method = np.max
text_agg_method = np.max 

emb_sims = []
emb_sims_max = []
for i in range (0, len (embs)):
    if (i % 1000) == 0:
        print (i)
    lin_cos_sim = cosine_similarity (embs[i], lookup_text_emb)
    lin_cos_sim = text_agg_method (lin_cos_sim, axis = 1)
    emb_sims.append (lin_cos_sim)
    emb_sims_max.append (agg_method (lin_cos_sim))
    
    

0
1000
2000
3000
4000


In [219]:
emb_sims_max [1]

1.0000000000000002

In [220]:
emb_sims_max [0:100]

[0.8427038,
 1.0000000000000002,
 0.87328947,
 0.8541685497959718,
 1.0000000000000002,
 0.9999999,
 0.8500843365069591,
 0.8769028008141451,
 0.8841082724194276,
 0.85008436,
 0.9999999,
 0.85008436,
 1.0000000000000002,
 0.99999994,
 1.0000000000000002,
 0.85008436,
 1.0000000000000002,
 0.8607826,
 0.8500843365069591,
 0.86093867,
 0.8624499122122617,
 0.8968295,
 0.8620199623511139,
 0.8500843365069591,
 0.99999994,
 0.8500843365069591,
 1.0000000000000002,
 1.0000000000000002,
 0.8427036851650482,
 0.85008436,
 1.0000000000000002,
 0.8518469169916202,
 0.8500843365069591,
 0.8841082724194276,
 0.8500843365069591,
 0.8841082724194276,
 0.8427036851650482,
 0.85008436,
 0.8500843365069591,
 0.8681443,
 0.8841082,
 0.9999999,
 0.85008436,
 0.85008436,
 0.8624499122122617,
 0.99999994,
 1.0000000000000002,
 0.82852024,
 0.8620199623511139,
 0.8500843365069591,
 0.85008436,
 0.8427038,
 0.9999999,
 0.8500843365069591,
 0.875910588479086,
 0.8968294526476451,
 1.0000000000000002,
 0.917

In [169]:
np.max (lin_cos_sim)

0.84270376

In [51]:
import gensim

In [52]:
import gensim.downloader as api

In [3]:
a = api.info()


In [ ]:
list (a["models"].keys())

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [14]:
emb_model = api.load ("glove-twitter-25")

In [19]:
emb_model ['a'].shape[0]

25

In [510]:
gensim.models.word2vec.Word2VecKeyedVectors()

<module 'gensim.models' from 'C:\\Users\\dfleetwood\\PycharmProjects\\text_analysis\\venv\\lib\\site-packages\\gensim\\models\\__init__.py'>